
package interfaces;

import acceso.Bibliotecario;
import inventario.Almacenamiento;
import inventario.Baja;
import inventario.Ejemplar;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;


public class DarDeBaja extends javax.swing.JFrame {

    
    private Bibliotecario bibliotecario;
    public DarDeBaja(Bibliotecario b) {
        initComponents();
        this.bibliotecario=b;
    }
    
    public DarDeBaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DarDeBaja = new javax.swing.JButton();
        IDText = new javax.swing.JTextField();
        Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MotivoBaja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID unico del ejemplar");

        DarDeBaja.setText("Dar de Baja");
        DarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarDeBajaActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Motivo Baja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addComponent(DarDeBaja)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MotivoBaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDText, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MotivoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DarDeBaja)
                    .addComponent(Volver))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarDeBajaActionPerformed
       if(bibliotecario==null){
           JOptionPane.showMessageDialog(null, "necesitas iniciar sesion para realizar esta accion");   
           this.setVisible(false);
           new Login().setVisible(true);
       }else{
        
       Almacenamiento a = new Almacenamiento();
       a.obtenerObras("recursos/ListadoDeObras.txt");
       a.obtenerEjemplares("recursos/ListadoDeEjemplares.txt");
       List<Ejemplar> ejemplarDisponibles = a.getEjemplarDisponibles();
       if(IDText.getText().equals("")||this.MotivoBaja.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Completar los campos");
       }else{
       String IDUnico=IDText.getText();
       Ejemplar ejemplar=null;
       for(Ejemplar ejem:ejemplarDisponibles){
           if(ejem.getIdUnico().equalsIgnoreCase(IDUnico)){
               ejemplar=ejem;
               break;
           }
       }
       if(ejemplar==null){
           JOptionPane.showMessageDialog(null, "No se encontro ningun ejemplar disponible con el id unico: "+IDUnico);   
           this.setVisible(false);
           new  Administracion(bibliotecario).setVisible(true);
      }else{
        LocalDate hoy=LocalDate.now(); 
        String motivo=MotivoBaja.getText();
        ejemplar.setBaja(new Baja(hoy,motivo,ejemplar.getLugarFisico()));
        a.modificarCSV("recursos/ListadoDeEjemplares.txt",ejemplar.toCSV(1), ejemplar.darDeBajaCSV());
        JOptionPane.showMessageDialog(null, "ejemplar dado de baja correctamente");   
        this.setVisible(false);
        new Administracion(bibliotecario).setVisible(true);
      }
       
      }
     }
    }//GEN-LAST:event_DarDeBajaActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        new Administracion(bibliotecario).setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DarDeBaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DarDeBaja;
    private javax.swing.JTextField IDText;
    private javax.swing.JTextField MotivoBaja;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
