/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import acceso.Devolucion;
import acceso.Lector;
import acceso.Multa;
import acceso.Prestamo;
import inventario.Almacenamiento;
import inventario.Ejemplar;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Maty
 */
public class GenerarDevolucion extends javax.swing.JFrame {

    /**
     * Creates new form GenerarDevolucion
     */
    private String opcion;
    
    public GenerarDevolucion() {
        initComponents();
        tagParametroBuscar.setVisible(false);
        texto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TagBuscarPor = new javax.swing.JLabel();
        buscarPrestamoPor = new javax.swing.JComboBox<>();
        tagParametroBuscar = new javax.swing.JLabel();
        texto = new javax.swing.JTextField();
        BotonDevolver = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TagBuscarPor.setText("Buscar Prestamo Por: ");

        buscarPrestamoPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Lector", "Ejemplar"}));
        buscarPrestamoPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPrestamoPorActionPerformed(evt);
            }
        });

        BotonDevolver.setText("Devolver");
        BotonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDevolverActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TagBuscarPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarPrestamoPor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tagParametroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TagBuscarPor)
                    .addComponent(tagParametroBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarPrestamoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarPrestamoPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPrestamoPorActionPerformed
        opcion=buscarPrestamoPor.getSelectedItem().toString();
        switch(opcion){
            case "Lector":
                tagParametroBuscar.setText("numero dni del lector: ");
                tagParametroBuscar.setVisible(true);
                texto.setVisible(true);
                break;
            case "Ejemplar":
                tagParametroBuscar.setText("id unico del ejemplar: ");
                tagParametroBuscar.setVisible(true);
                texto.setVisible(true);
                break;
        }
                
    }//GEN-LAST:event_buscarPrestamoPorActionPerformed

    private void BotonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDevolverActionPerformed
        Almacenamiento a = new Almacenamiento();
        a.obtenerObras("recursos/ListadoDeObras.txt");
        a.obtenerEjemplares("recursos/ListadoDeEjemplares.txt");
        a.obtenerPrestamos("recursos/ListaPrestamos.txt");
        List<Prestamo> prestamosActivos = a.getPrestamosActivos();
        Prestamo prestamo=null;
        
        
        switch(opcion){
            case "Lector":
                int dni=Integer.valueOf(texto.getText());
                for(Prestamo p:prestamosActivos){
                    if(p.getLector().getNumDocumento() == dni){
                        prestamo=p;
                        break;
                    }
                }
                break;
            case "Ejemplar":
                String idunico=texto.getText();
                for(Prestamo p:prestamosActivos){
                    if(p.getEjemplar().getIdUnico().equalsIgnoreCase(idunico)){
                        System.out.println(p.getEjemplar().getIdUnico()+"|"+idunico);
                        prestamo=p;
                        break;
                    }
                }
                break;
        }
        
        //verifica si la devolucion esta a tiempo o no
        LocalDate hoy=LocalDate.now();
        boolean fueradeTermino=false;
        if(hoy.isAfter(prestamo.getFechaDevolucion())){
            Lector lector = prestamo.getLector();
            lector.setMulta(new Multa(3,hoy));
            fueradeTermino=true;
        }
        
        Ejemplar ejemplar = prestamo.getEjemplar();
        //actualiza los datos de los txt
        //cambia la disponibilidad del ejemplar a 1=disponible
        a.modificarCSV("recursos/ListadoDeEjemplares.txt",ejemplar.toCSV(2), ejemplar.toCSV(1));
        //cambia la disponibilidad del prestamo a 2=terminado
        //no esta funcionando por alguna razon el idunico es distinto 
        a.modificarCSV("recursos/ListaPrestamos.txt", prestamo.toCSV(1),prestamo.toCSV(2));
        
        Devolucion devolucion=new Devolucion(hoy,fueradeTermino,prestamo);
        
         JOptionPane.showMessageDialog(null,"devolucion realizada con exito");
         this.setVisible(false);
         new Administracion().setVisible(true);
        

    }//GEN-LAST:event_BotonDevolverActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
        new Administracion().setVisible(true);    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarDevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDevolver;
    private javax.swing.JLabel TagBuscarPor;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> buscarPrestamoPor;
    private javax.swing.JLabel tagParametroBuscar;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
