package interfaces;

import acceso.Bibliotecario;
import inventario.Almacenamiento;
import inventario.Edicion;
import inventario.Obra;
import inventario.TipoObra;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lucia
 */
public class RegistrarObra extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarObra
     */
    Bibliotecario bibliotecario;
    public RegistrarObra(Bibliotecario b) {
        initComponents();
        this.setLocationRelativeTo(null);
        bibliotecario =b;
    }
    public RegistrarObra() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        isbnColeccionLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        subtituloLabel = new javax.swing.JLabel();
        autorLabel = new javax.swing.JLabel();
        autor2Label = new javax.swing.JLabel();
        autor3Label = new javax.swing.JLabel();
        generoLabel = new javax.swing.JLabel();
        caracteristicaLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        areaTematicaLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        editorialNombreLabel = new javax.swing.JLabel();
        paisLabel = new javax.swing.JLabel();
        numeroEdicionLabel = new javax.swing.JLabel();
        anioEdicionLabel = new javax.swing.JLabel();
        volumenesLabel = new javax.swing.JLabel();
        idiomaLabel = new javax.swing.JLabel();
        paginasLabel = new javax.swing.JLabel();
        formatoLabel = new javax.swing.JLabel();
        coleccionLabel = new javax.swing.JLabel();
        tituloTextField = new javax.swing.JTextField();
        subtituloTextField = new javax.swing.JTextField();
        autorTextField = new javax.swing.JTextField();
        autor2TextField = new javax.swing.JTextField();
        autor3TextField = new javax.swing.JTextField();
        generoTextField = new javax.swing.JTextField();
        caracteristicaTextField = new javax.swing.JTextField();
        isbnTextField = new javax.swing.JTextField();
        areaTematicaTextField = new javax.swing.JTextField();
        editorialTextField = new javax.swing.JTextField();
        paisTextField = new javax.swing.JTextField();
        numeroEdicionTextField = new javax.swing.JTextField();
        anioEdicionTextField = new javax.swing.JTextField();
        volumenesTextField = new javax.swing.JTextField();
        idiomaTextField = new javax.swing.JTextField();
        paginasTextField = new javax.swing.JTextField();
        formatoTextField = new javax.swing.JTextField();
        coleccionTextField = new javax.swing.JTextField();
        isbnColeccionTextField = new javax.swing.JTextField();
        volverJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelRegistrarObra = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registrarLabel = new javax.swing.JLabel();
        ComboBoxTIPO = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(219, 247, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isbnColeccionLabel.setBackground(new java.awt.Color(0, 0, 0));
        isbnColeccionLabel.setText("ISBN de colección");
        jPanel1.add(isbnColeccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 130, -1));

        tituloLabel.setText("Titulo");
        jPanel1.add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        subtituloLabel.setText("Subtitulo");
        jPanel1.add(subtituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        autorLabel.setText("Autor");
        jPanel1.add(autorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        autor2Label.setText("Autor 2");
        jPanel1.add(autor2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        autor3Label.setText("Autor 3");
        jPanel1.add(autor3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        generoLabel.setText("Genero");
        jPanel1.add(generoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        caracteristicaLabel.setText("Caracteristica");
        jPanel1.add(caracteristicaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        isbnLabel.setText("ISBN");
        jPanel1.add(isbnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        areaTematicaLabel.setBackground(new java.awt.Color(0, 0, 0));
        areaTematicaLabel.setText("Area Temática");
        jPanel1.add(areaTematicaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        tipoLabel.setText("Tipo");
        jPanel1.add(tipoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        editorialNombreLabel.setText("Editorial");
        jPanel1.add(editorialNombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        paisLabel.setText("País");
        jPanel1.add(paisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        numeroEdicionLabel.setText("Numero de edición");
        jPanel1.add(numeroEdicionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        anioEdicionLabel.setText("Año de edición");
        jPanel1.add(anioEdicionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        volumenesLabel.setText("Volúmenes");
        jPanel1.add(volumenesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        idiomaLabel.setText("Idioma");
        jPanel1.add(idiomaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        paginasLabel.setText("Páginas");
        jPanel1.add(paginasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        formatoLabel.setText("Formato");
        jPanel1.add(formatoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        coleccionLabel.setText("Colección");
        jPanel1.add(coleccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        tituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(tituloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, -1));

        subtituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtituloTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(subtituloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 210, -1));
        jPanel1.add(autorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, -1));
        jPanel1.add(autor2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 210, -1));
        jPanel1.add(autor3TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 210, -1));
        jPanel1.add(generoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 210, -1));
        jPanel1.add(caracteristicaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 210, -1));
        jPanel1.add(isbnTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 210, -1));
        jPanel1.add(areaTematicaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 210, -1));
        jPanel1.add(editorialTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 210, -1));
        jPanel1.add(paisTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 210, -1));
        jPanel1.add(numeroEdicionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 210, -1));
        jPanel1.add(anioEdicionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 210, -1));
        jPanel1.add(volumenesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 210, -1));
        jPanel1.add(idiomaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 210, -1));
        jPanel1.add(paginasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 210, -1));
        jPanel1.add(formatoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 210, -1));
        jPanel1.add(coleccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 210, -1));
        jPanel1.add(isbnColeccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 210, -1));

        volverJButton.setText("Volver");
        volverJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(volverJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabelRegistrarObra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRegistrarObra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarObra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrarObra.setText("Registrar Obra");
        jLabelRegistrarObra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarObra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarObra, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        registrarLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarLabel.setText("Registrar");
        registrarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 120, 40));

        ComboBoxTIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"","LIBRO","ENSAYO","REVISTA","TESIS","MANUAL"}));
        jPanel1.add(ComboBoxTIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subtituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtituloTextFieldActionPerformed

    private void tituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTextFieldActionPerformed

    private void volverJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverJButtonActionPerformed
        this.setVisible(false);
        new Administracion(bibliotecario).setVisible(true);
    }//GEN-LAST:event_volverJButtonActionPerformed

    private void registrarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarLabelMouseClicked
        registrarObra();
        this.setVisible(false);
        new Administracion(bibliotecario).setVisible(true);
    }//GEN-LAST:event_registrarLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTIPO;
    private javax.swing.JLabel anioEdicionLabel;
    private javax.swing.JTextField anioEdicionTextField;
    private javax.swing.JLabel areaTematicaLabel;
    private javax.swing.JTextField areaTematicaTextField;
    private javax.swing.JLabel autor2Label;
    private javax.swing.JTextField autor2TextField;
    private javax.swing.JLabel autor3Label;
    private javax.swing.JTextField autor3TextField;
    private javax.swing.JLabel autorLabel;
    private javax.swing.JTextField autorTextField;
    private javax.swing.JLabel caracteristicaLabel;
    private javax.swing.JTextField caracteristicaTextField;
    private javax.swing.JLabel coleccionLabel;
    private javax.swing.JTextField coleccionTextField;
    private javax.swing.JLabel editorialNombreLabel;
    private javax.swing.JTextField editorialTextField;
    private javax.swing.JLabel formatoLabel;
    private javax.swing.JTextField formatoTextField;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JTextField generoTextField;
    private javax.swing.JLabel idiomaLabel;
    private javax.swing.JTextField idiomaTextField;
    private javax.swing.JLabel isbnColeccionLabel;
    private javax.swing.JTextField isbnColeccionTextField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JLabel jLabelRegistrarObra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel numeroEdicionLabel;
    private javax.swing.JTextField numeroEdicionTextField;
    private javax.swing.JLabel paginasLabel;
    private javax.swing.JTextField paginasTextField;
    private javax.swing.JLabel paisLabel;
    private javax.swing.JTextField paisTextField;
    private javax.swing.JLabel registrarLabel;
    private javax.swing.JLabel subtituloLabel;
    private javax.swing.JTextField subtituloTextField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JLabel volumenesLabel;
    private javax.swing.JTextField volumenesTextField;
    private javax.swing.JButton volverJButton;
    // End of variables declaration//GEN-END:variables

    
    public void registrarObra(){
        Almacenamiento a = new Almacenamiento();
        a.obtenerObras("recursos/ListadoDeObras.txt");
        List<Obra> obras = a.getObras();
        
        TipoObra tipoObra = TipoObra.LIBRO;
         switch (ComboBoxTIPO.getSelectedItem().toString()) {
                        case "LIBRO":
                            tipoObra = TipoObra.LIBRO;
                            break;
                        case "REVISTA":
                            tipoObra = TipoObra.REVISTA;
                            break;
                        case "ENSAYO":
                            tipoObra = TipoObra.ENSAYO;
                            break;
                        case "TESIS":
                            tipoObra = TipoObra.TESIS;
                            break;
                        case "MANUAL":
                            tipoObra = TipoObra.MANUAL;
                            break;
                    }
        Obra obra = new Obra(tituloTextField.getText(), subtituloTextField.getText(), autorTextField.getText(), autor2TextField.getText(), autor3TextField.getText(), generoTextField.getText(), caracteristicaTextField.getText(), isbnTextField.getText(), 0,areaTematicaTextField.getText(), tipoObra, new Edicion(editorialTextField.getText(),numeroEdicionTextField.getText(), numeroEdicionTextField.getText(), Integer.parseInt(anioEdicionTextField.getText()), Integer.parseInt(volumenesTextField.getText()), idiomaTextField.getText(), Integer.parseInt(paginasTextField.getText()), formatoTextField.getText()), isbnTextField.getText(), "", 0, 0);
        boolean esta= false;
        for (Obra obra1 : obras) {
            if(obra.getISBN().equals(obra1.getISBN())){
                esta = true;
                break;
            }
        }
        if (!esta){
            new Almacenamiento().escribirCSV("recursos/ListadoDeObras.txt", tituloTextField.getText()+","+subtituloTextField.getText()+","+autorTextField.getText()+","+autor2TextField.getText()+","+autor3TextField.getText()+","+generoTextField.getText()+","+caracteristicaTextField.getText()+","+isbnTextField.getText()+","+areaTematicaTextField.getText()+","+ComboBoxTIPO.getSelectedItem().toString()+","+editorialTextField.getText()+","+paisTextField.getText()+","+numeroEdicionTextField.getText()+","+anioEdicionTextField.getText()+","+volumenesTextField.getText()+","+idiomaTextField.getText()+","+paginasTextField.getText()+","+formatoTextField.getText()+","+coleccionTextField.getText()+","+isbnColeccionTextField.getText());
        } else {JOptionPane.showMessageDialog(null, "Ya existe esta obra!", "Ventana emergente", 1);}
    }     
}
